/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    weaponsPassportNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Company
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Company
     */
    updated?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    cvr?: string | null;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): value is Company {
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'weaponsPassportNumber': json['weaponsPassportNumber'] == null ? undefined : json['weaponsPassportNumber'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'name': json['name'] == null ? undefined : json['name'],
        'cvr': json['cvr'] == null ? undefined : json['cvr'],
    };
}

export function CompanyToJSON(json: any): Company {
    return CompanyToJSONTyped(json, false);
}

export function CompanyToJSONTyped(value?: Company | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phone': value['phone'],
        'email': value['email'],
        'weaponsPassportNumber': value['weaponsPassportNumber'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'createdBy': value['createdBy'],
        'updated': value['updated'] == null ? undefined : ((value['updated'] as any).toISOString()),
        'updatedBy': value['updatedBy'],
        'name': value['name'],
        'cvr': value['cvr'],
    };
}

