/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';

/**
 * 
 * @export
 * @interface Discharge
 */
export interface Discharge {
    /**
     * 
     * @type {number}
     * @memberof Discharge
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    weaponID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    systemNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    barrelNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    basepieceNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Discharge
     */
    dischargedToPersonId?: number | null;
    /**
     * 
     * @type {Person}
     * @memberof Discharge
     */
    dischargedToPerson?: Person;
    /**
     * 
     * @type {number}
     * @memberof Discharge
     */
    dischargedToCompanyId?: number | null;
    /**
     * 
     * @type {Company}
     * @memberof Discharge
     */
    dischargedToCompany?: Company;
    /**
     * 
     * @type {Date}
     * @memberof Discharge
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Discharge
     */
    updated?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Discharge
     */
    updatedBy?: string | null;
}

/**
 * Check if a given object implements the Discharge interface.
 */
export function instanceOfDischarge(value: object): value is Discharge {
    return true;
}

export function DischargeFromJSON(json: any): Discharge {
    return DischargeFromJSONTyped(json, false);
}

export function DischargeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discharge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'weaponID': json['weaponID'] == null ? undefined : json['weaponID'],
        'systemNumber': json['systemNumber'] == null ? undefined : json['systemNumber'],
        'barrelNumber': json['barrelNumber'] == null ? undefined : json['barrelNumber'],
        'basepieceNumber': json['basepieceNumber'] == null ? undefined : json['basepieceNumber'],
        'dischargedToPersonId': json['dischargedToPersonId'] == null ? undefined : json['dischargedToPersonId'],
        'dischargedToPerson': json['dischargedToPerson'] == null ? undefined : PersonFromJSON(json['dischargedToPerson']),
        'dischargedToCompanyId': json['dischargedToCompanyId'] == null ? undefined : json['dischargedToCompanyId'],
        'dischargedToCompany': json['dischargedToCompany'] == null ? undefined : CompanyFromJSON(json['dischargedToCompany']),
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
    };
}

export function DischargeToJSON(json: any): Discharge {
    return DischargeToJSONTyped(json, false);
}

export function DischargeToJSONTyped(value?: Discharge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'weaponID': value['weaponID'],
        'systemNumber': value['systemNumber'],
        'barrelNumber': value['barrelNumber'],
        'basepieceNumber': value['basepieceNumber'],
        'dischargedToPersonId': value['dischargedToPersonId'],
        'dischargedToPerson': PersonToJSON(value['dischargedToPerson']),
        'dischargedToCompanyId': value['dischargedToCompanyId'],
        'dischargedToCompany': CompanyToJSON(value['dischargedToCompany']),
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'createdBy': value['createdBy'],
        'updated': value['updated'] == null ? undefined : ((value['updated'] as any).toISOString()),
        'updatedBy': value['updatedBy'],
    };
}

