/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LoadfunctionNullable = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type LoadfunctionNullable = typeof LoadfunctionNullable[keyof typeof LoadfunctionNullable];


export function instanceOfLoadfunctionNullable(value: any): boolean {
    for (const key in LoadfunctionNullable) {
        if (Object.prototype.hasOwnProperty.call(LoadfunctionNullable, key)) {
            if (LoadfunctionNullable[key as keyof typeof LoadfunctionNullable] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LoadfunctionNullableFromJSON(json: any): LoadfunctionNullable {
    return LoadfunctionNullableFromJSONTyped(json, false);
}

export function LoadfunctionNullableFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoadfunctionNullable {
    return json as LoadfunctionNullable;
}

export function LoadfunctionNullableToJSON(value?: LoadfunctionNullable | null): any {
    return value as any;
}

export function LoadfunctionNullableToJSONTyped(value: any, ignoreDiscriminator: boolean): LoadfunctionNullable {
    return value as LoadfunctionNullable;
}

