/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    weaponsPassportNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    updated?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    firstname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    lastname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    cpr?: string | null;
}

/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'weaponsPassportNumber': json['weaponsPassportNumber'] == null ? undefined : json['weaponsPassportNumber'],
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'cpr': json['cpr'] == null ? undefined : json['cpr'],
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phone': value['phone'],
        'email': value['email'],
        'weaponsPassportNumber': value['weaponsPassportNumber'],
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'createdBy': value['createdBy'],
        'updated': value['updated'] == null ? undefined : ((value['updated'] as any).toISOString()),
        'updatedBy': value['updatedBy'],
        'firstname': value['firstname'],
        'lastname': value['lastname'],
        'cpr': value['cpr'],
    };
}

