/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPasswordUpdateDTO
 */
export interface UserPasswordUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserPasswordUpdateDTO
     */
    oldPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPasswordUpdateDTO
     */
    newPassword?: string | null;
}

/**
 * Check if a given object implements the UserPasswordUpdateDTO interface.
 */
export function instanceOfUserPasswordUpdateDTO(value: object): value is UserPasswordUpdateDTO {
    return true;
}

export function UserPasswordUpdateDTOFromJSON(json: any): UserPasswordUpdateDTO {
    return UserPasswordUpdateDTOFromJSONTyped(json, false);
}

export function UserPasswordUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPasswordUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'oldPassword': json['oldPassword'] == null ? undefined : json['oldPassword'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function UserPasswordUpdateDTOToJSON(json: any): UserPasswordUpdateDTO {
    return UserPasswordUpdateDTOToJSONTyped(json, false);
}

export function UserPasswordUpdateDTOToJSONTyped(value?: UserPasswordUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
    };
}

