/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateDTO
 */
export interface UserCreateDTO {
    /**
     * 
     * @type {string}
     * @memberof UserCreateDTO
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreateDTO
     */
    password?: string | null;
}

/**
 * Check if a given object implements the UserCreateDTO interface.
 */
export function instanceOfUserCreateDTO(value: object): value is UserCreateDTO {
    return true;
}

export function UserCreateDTOFromJSON(json: any): UserCreateDTO {
    return UserCreateDTOFromJSONTyped(json, false);
}

export function UserCreateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserCreateDTOToJSON(json: any): UserCreateDTO {
    return UserCreateDTOToJSONTyped(json, false);
}

export function UserCreateDTOToJSONTyped(value?: UserCreateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

