/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';
import type { WeaponType } from './WeaponType';
import {
    WeaponTypeFromJSON,
    WeaponTypeFromJSONTyped,
    WeaponTypeToJSON,
    WeaponTypeToJSONTyped,
} from './WeaponType';
import type { LoadfunctionNullable } from './LoadfunctionNullable';
import {
    LoadfunctionNullableFromJSON,
    LoadfunctionNullableFromJSONTyped,
    LoadfunctionNullableToJSON,
    LoadfunctionNullableToJSONTyped,
} from './LoadfunctionNullable';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';
import type { WeaponStatus } from './WeaponStatus';
import {
    WeaponStatusFromJSON,
    WeaponStatusFromJSONTyped,
    WeaponStatusToJSON,
    WeaponStatusToJSONTyped,
} from './WeaponStatus';

/**
 * 
 * @export
 * @interface Weapon
 */
export interface Weapon {
    /**
     * 
     * @type {number}
     * @memberof Weapon
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    manufacturer?: string | null;
    /**
     * 
     * @type {LoadfunctionNullable}
     * @memberof Weapon
     */
    loadFunction?: LoadfunctionNullable | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    loadFunctionFreetext?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    systemNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    barrelNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    basepieceNumber?: string | null;
    /**
     * 
     * @type {WeaponType}
     * @memberof Weapon
     */
    type?: WeaponType;
    /**
     * 
     * @type {WeaponStatus}
     * @memberof Weapon
     */
    status?: WeaponStatus;
    /**
     * 
     * @type {Date}
     * @memberof Weapon
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    createdBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Weapon
     */
    updated?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Weapon
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Weapon
     */
    discharged?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Weapon
     */
    submitterPersonId?: number | null;
    /**
     * 
     * @type {Person}
     * @memberof Weapon
     */
    submitterPerson?: Person;
    /**
     * 
     * @type {number}
     * @memberof Weapon
     */
    submitterCompanyId?: number | null;
    /**
     * 
     * @type {Company}
     * @memberof Weapon
     */
    submitterCompany?: Company;
    /**
     * 
     * @type {number}
     * @memberof Weapon
     */
    dischargedToPersonId?: number | null;
    /**
     * 
     * @type {Person}
     * @memberof Weapon
     */
    dischargedToPerson?: Person;
    /**
     * 
     * @type {number}
     * @memberof Weapon
     */
    dischargedToCompanyId?: number | null;
    /**
     * 
     * @type {Company}
     * @memberof Weapon
     */
    dischargedToCompany?: Company;
}



/**
 * Check if a given object implements the Weapon interface.
 */
export function instanceOfWeapon(value: object): value is Weapon {
    return true;
}

export function WeaponFromJSON(json: any): Weapon {
    return WeaponFromJSONTyped(json, false);
}

export function WeaponFromJSONTyped(json: any, ignoreDiscriminator: boolean): Weapon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'manufacturer': json['manufacturer'] == null ? undefined : json['manufacturer'],
        'loadFunction': json['loadFunction'] == null ? undefined : LoadfunctionNullableFromJSON(json['loadFunction']),
        'loadFunctionFreetext': json['loadFunctionFreetext'] == null ? undefined : json['loadFunctionFreetext'],
        'systemNumber': json['systemNumber'] == null ? undefined : json['systemNumber'],
        'barrelNumber': json['barrelNumber'] == null ? undefined : json['barrelNumber'],
        'basepieceNumber': json['basepieceNumber'] == null ? undefined : json['basepieceNumber'],
        'type': json['type'] == null ? undefined : WeaponTypeFromJSON(json['type']),
        'status': json['status'] == null ? undefined : WeaponStatusFromJSON(json['status']),
        'created': json['created'] == null ? undefined : (new Date(json['created'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updated': json['updated'] == null ? undefined : (new Date(json['updated'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'discharged': json['discharged'] == null ? undefined : (new Date(json['discharged'])),
        'submitterPersonId': json['submitterPersonId'] == null ? undefined : json['submitterPersonId'],
        'submitterPerson': json['submitterPerson'] == null ? undefined : PersonFromJSON(json['submitterPerson']),
        'submitterCompanyId': json['submitterCompanyId'] == null ? undefined : json['submitterCompanyId'],
        'submitterCompany': json['submitterCompany'] == null ? undefined : CompanyFromJSON(json['submitterCompany']),
        'dischargedToPersonId': json['dischargedToPersonId'] == null ? undefined : json['dischargedToPersonId'],
        'dischargedToPerson': json['dischargedToPerson'] == null ? undefined : PersonFromJSON(json['dischargedToPerson']),
        'dischargedToCompanyId': json['dischargedToCompanyId'] == null ? undefined : json['dischargedToCompanyId'],
        'dischargedToCompany': json['dischargedToCompany'] == null ? undefined : CompanyFromJSON(json['dischargedToCompany']),
    };
}

export function WeaponToJSON(json: any): Weapon {
    return WeaponToJSONTyped(json, false);
}

export function WeaponToJSONTyped(value?: Weapon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'manufacturer': value['manufacturer'],
        'loadFunction': LoadfunctionNullableToJSON(value['loadFunction']),
        'loadFunctionFreetext': value['loadFunctionFreetext'],
        'systemNumber': value['systemNumber'],
        'barrelNumber': value['barrelNumber'],
        'basepieceNumber': value['basepieceNumber'],
        'type': WeaponTypeToJSON(value['type']),
        'status': WeaponStatusToJSON(value['status']),
        'created': value['created'] == null ? undefined : ((value['created']).toISOString()),
        'createdBy': value['createdBy'],
        'updated': value['updated'] == null ? undefined : ((value['updated'] as any).toISOString()),
        'updatedBy': value['updatedBy'],
        'discharged': value['discharged'] == null ? undefined : ((value['discharged'] as any).toISOString()),
        'submitterPersonId': value['submitterPersonId'],
        'submitterPerson': PersonToJSON(value['submitterPerson']),
        'submitterCompanyId': value['submitterCompanyId'],
        'submitterCompany': CompanyToJSON(value['submitterCompany']),
        'dischargedToPersonId': value['dischargedToPersonId'],
        'dischargedToPerson': PersonToJSON(value['dischargedToPerson']),
        'dischargedToCompanyId': value['dischargedToCompanyId'],
        'dischargedToCompany': CompanyToJSON(value['dischargedToCompany']),
    };
}

