/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WeaponStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type WeaponStatus = typeof WeaponStatus[keyof typeof WeaponStatus];


export function instanceOfWeaponStatus(value: any): boolean {
    for (const key in WeaponStatus) {
        if (Object.prototype.hasOwnProperty.call(WeaponStatus, key)) {
            if (WeaponStatus[key as keyof typeof WeaponStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WeaponStatusFromJSON(json: any): WeaponStatus {
    return WeaponStatusFromJSONTyped(json, false);
}

export function WeaponStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeaponStatus {
    return json as WeaponStatus;
}

export function WeaponStatusToJSON(value?: WeaponStatus | null): any {
    return value as any;
}

export function WeaponStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WeaponStatus {
    return value as WeaponStatus;
}

