/* tslint:disable */
/* eslint-disable */
/**
 * VaabenportalenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WeaponType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type WeaponType = typeof WeaponType[keyof typeof WeaponType];


export function instanceOfWeaponType(value: any): boolean {
    for (const key in WeaponType) {
        if (Object.prototype.hasOwnProperty.call(WeaponType, key)) {
            if (WeaponType[key as keyof typeof WeaponType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WeaponTypeFromJSON(json: any): WeaponType {
    return WeaponTypeFromJSONTyped(json, false);
}

export function WeaponTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeaponType {
    return json as WeaponType;
}

export function WeaponTypeToJSON(value?: WeaponType | null): any {
    return value as any;
}

export function WeaponTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WeaponType {
    return value as WeaponType;
}

